yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница групп
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание поста
    path("create/", views.post_create, name="post_create"),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/auth/logged_out.html'),
        name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/auth/login.html'),
         name='login'),
    path('password-change/',
         PasswordChangeView.as_view
         (template_name='users/auth/password_change.html'),
         name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view
         (template_name='users/auth/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view
         (template_name='users/auth/password_reset_form.html'),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view
         (template_name='users/auth/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view
         (template_name='users/auth/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view
         (template_name='users/auth/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

# Добавляем к путям из приложения posts пространство имён posts
urlpatterns = [
    path('auth/', include('users.urls')),
    path("auth/", include("django.contrib.auth.urls")),
    path('', include('posts.urls', namespace='posts')),
    path('group/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Название группы"
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="Уникальный адрес группы"
    )
    description = models.TextField(verbose_name="Описание сообществ")

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="Текст поста")
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации поста"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор поста"
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name="Группа"
    )

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        widgets = {
            'text': forms.Textarea(attrs={'rows': 7}),
        }

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.POST_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """View-функция для страницы сообщества"""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    template = 'posts/group_list.html'
    paginator = Paginator(posts, settings.POST_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'paginator': paginator,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user_obj = get_object_or_404(User, username=username)
    posts = user_obj.posts.all()
    paginator = Paginator(posts, settings.POST_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    context = {
        'user_obj': user_obj,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/post_detail.html'
    context = {
        'post': post,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    is_edit = get_object_or_404(Post, pk=post_id)
    if request.user != is_edit.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=is_edit)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    context = {'form': form, 'is_edit': True}
    return render(request, template, context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users//auth/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я Анастасия</h1>
<p>
  Я начинающий Python разработчик, с детства увлекаюсь программированием и не представляю своей жизни без этого.
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
  <meta charset="utf-8"> <!-- Кодировка сайта -->
  <!-- Сайт готов работать с мобильными устройствами -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Загружаем фав-иконки -->
  <link rel="icon" href="{% static 'img/fav/favicon.ico' type="image" %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <!-- Подключен файл со стандартными стилями бустрап -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>
    {% block title %}
    {% endblock %}
  </title>
</head>
<body>
<header>
  {% include 'includes/header.html' %}
</header>
<main>
  {% block content %}
  {% endblock %}
</main>
<footer>
  {% include 'includes/footer.html' %}
</footer>
</body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/forms.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}
<form method="post"{% if action_url %}action="{% url action_url %}"
{% endif %}>
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group row my-3"
         {% if field.field.required %}aria-required="true"
         {% else %}aria-required="false"
         {% endif %}>
      <label for="{{ field.id_for_label }}">{{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
      </label>
      <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
    </div>
  {% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте #}
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {%  if view_name == 'about:tech' %}active {% endif %}"
             href="{% url 'about:tech' %}">Технологии
          </a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'posts:post_create' %} active
            {% endif %}" href="{% url 'posts:post_create' %}">
            Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {%  if view_name == 'users:password_change' %}
               active {% endif %}"
               href="{% url 'users:password_change' %}">
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {%  if view_name == 'users:logout' %}
               active {% endif %}"
               href="{% url 'users:logout' %}">
              Выйти
            </a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {%  if view_name == 'users:login' %}
               active {% endif %}"
               href="{% url 'users:login' %}">
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {%  if view_name == 'users:signup' %}
               active {% endif %}"
               href="{% url 'users:signup' %}">
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
        {# Конец добавленого в спринте #}
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_item.html
<article>
  <ul>
    <li>
      Автор: {{  post.author  }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{  post.pub_date |date:"D d M Y" }}
    </li>
  </ul>
  <p>
    {{  post.text  }}
  </p>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
</article>

{% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}

{% if not forloop.last %}<hr>{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %} Редактировать запись
{% else %} Новый пост {% endif %} {% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}Редактировать запись{% else %}
            Новый пост{% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/forms.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p> {{ group.description }} </p>
    {% for post in page_obj %}
      {% include "includes/post_item.html" with post=post %}
    {% endfor %}
    {% if page_obj.has_other_pages %}
      {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
    {% endif %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  <div class="container py-5">
  <h1> Все посты </h1>
    {% for post in page_obj %}
      {% include "includes/post_item.html" with post=post %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% if page_obj.has_other_pages %}
      {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
    {% endif %}
  </div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
    Пост {{ post| truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{  post.pub_date |date:"d E Y" }}
        </li>
        <li class="list-group-item">
          Группа:
          {% if post.group %}
          {{ post.group }}
          {% else %}
            ---Пусто---
          {% endif %}
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ user.posts.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p> {{ post.text }} </p>
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        редактировать запись
      </a>
    </article>
  </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ user_obj }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>
      Все посты пользователя {{ user_obj }}
    </h1>
    <h3> Всего постов: {{ page_obj.paginator.count }} </h3>
    {% for post in page_obj %}
      {% include "includes/post_item.html" with post=post %}
    {% endfor %}
    {% if page_obj.has_other_pages %}
      {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
    {% endif %}
  </div>
{% endblock content %}